"""New schemas

Revision ID: 02f7ac0ce877
Revises: ca4ad9cf8d3b
Create Date: 2024-08-05 16:31:10.012902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02f7ac0ce877'
down_revision: Union[str, None] = 'ca4ad9cf8d3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
