"""'News'

Revision ID: 48d872fe5124
Revises: 02f7ac0ce877
Create Date: 2024-08-05 18:08:57.384673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48d872fe5124'
down_revision: Union[str, None] = '02f7ac0ce877'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'post_likes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('post_likes', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
